SET search_path TO app, public;
ALTER TABLE role_family ADD COLUMN IF NOT EXISTS direct_tags jsonb NOT NULL DEFAULT '[]';
ALTER TABLE role_family ADD COLUMN IF NOT EXISTS skill_mapping jsonb NOT NULL DEFAULT '{}';
UPDATE role_family SET direct_tags=CASE key WHEN 'RELATIONSHIP_EXECUTIVE' THEN '["BFSI_SALES","FIELD_SALES"]'::jsonb WHEN 'CUSTOMER_SERVICE_ASSOCIATE' THEN '["CUSTOMER_SERVICE","BFSI_SERVICE"]'::jsonb WHEN 'SALES_ASSOCIATE' THEN '["RETAIL_SALES","SALES"]'::jsonb ELSE transferable END;
UPDATE role_family SET skill_mapping='{"BFSI_SALES":["FIELD_SALES","TELECOM_SALES","SALES"],"CUSTOMER_COMMUNICATION":["CUSTOMER_SERVICE","BFSI_SERVICE","RETAIL_SALES"],"TARGET_ACHIEVEMENT":["FIELD_SALES","TELECOM_SALES","RETAIL_SALES"],"PRODUCT_KNOWLEDGE":["BFSI_SERVICE","COMMERCE_GRADUATE"]}' WHERE industry_key='BFSI';
