import {sql} from '@/lib/db';
import {ManagedForm} from './form';
import {requireRole} from '@/lib/auth';
export const dynamic='force-dynamic';
const Input=({name,label,value,type='text'}:{name:string;label:string;value?:string|number;type?:string})=><label className="field">{label}<input name={name} defaultValue={value} type={type} step={type==='number'?'any':undefined}/></label>;
export default async function Manage(){
 await requireRole(['ADMIN','OPERATIONS']);
 const [employers,partners,sites,localities,roles,industries,configs,attrs,policies]=await Promise.all([
 sql`SELECT * FROM app.employer_organisation ORDER BY id`,sql`SELECT * FROM app.partner ORDER BY id`,sql`SELECT * FROM app.partner_site ORDER BY id`,sql`SELECT * FROM app.locality ORDER BY display_name`,sql`SELECT * FROM app.role_family ORDER BY display_name`,sql`SELECT * FROM app.industry ORDER BY display_name`,sql`SELECT * FROM app.role_configuration ORDER BY id`,sql`SELECT * FROM app.attribute_definition ORDER BY display_name`,sql`SELECT * FROM app.commercial_policy WHERE active`]);
 const select=(name:string,rows:any[],key:string,label:string,selected?:string)=><select name={name} defaultValue={selected}>{rows.map(row=><option key={row[key]} value={row[key]}>{row[label]}</option>)}</select>;
 return <main className="page"><h1>Manage organisations & catalogue</h1><p>Edit records, add localities and partner sites, and configure new roles. Changes are recorded in Audit.</p>
 <section className="card card-body" id="employers"><h2>Employers</h2>{employers.map(e=><details key={e.id}><summary>{e.brand_name} · Edit</summary><ManagedForm kind="employer" id={e.id}><Input name="legal_name" label="Legal name" value={e.legal_name}/><Input name="brand_name" label="Brand" value={e.brand_name}/><Input name="gst_pan" label="GST / PAN" value={e.gst_pan}/><Input name="billing_contact" label="Billing contact" value={e.billing_contact}/></ManagedForm></details>)}</section>
 <section className="card card-body" id="partners"><h2>Partners & sites</h2>{partners.map(p=><details key={p.id}><summary>{p.name} · Edit / add site</summary><ManagedForm kind="partner" id={p.id}><Input name="name" label="Name" value={p.name}/><Input name="pan" label="PAN" value={p.pan}/><Input name="payout_upi" label="Demo payout reference" value={p.payout_upi}/><fieldset><legend>Service localities</legend>{localities.map(l=><label key={l.key}><input type="checkbox" name="localities" value={l.key} defaultChecked={p.service_localities.includes(l.key)}/>{l.display_name} </label>)}</fieldset><fieldset><legend>Sourcing capabilities</legend>{roles.map(role=><label key={role.key}><input type="checkbox" name="capabilities" value={role.industry_key+'/'+role.key} defaultChecked={p.capabilities.includes(role.industry_key+'/'+role.key)}/>{role.display_name} </label>)}</fieldset></ManagedForm><h3>Add site</h3><ManagedForm kind="site" id={p.id}><Input name="name" label="Site name"/><Input name="address" label="Address"/>{select('locality',localities,'key','display_name')}<p>New sites start suspended until Operations verifies them.</p></ManagedForm>{sites.filter(s=>s.partner_id===p.id).map(s=><div key={s.id}><ManagedForm kind="site_edit" id={s.id}><Input name="name" label="Site name" value={s.name||s.id}/><Input name="address" label="Address" value={s.address||''}/>{select('locality',localities,'key','display_name',s.locality_key)}</ManagedForm><ManagedForm kind="site_status" id={s.id}><p>{s.name||s.id} · {s.partner_code}</p><select name="status" defaultValue={s.status}><option>ACTIVE</option><option>SUSPENDED</option><option>REVOKED</option></select></ManagedForm></div>)}</details>)}</section>
 <section className="card card-body" id="localities"><h2>Add locality</h2><ManagedForm kind="locality"><Input name="name" label="Locality name"/><Input name="key" label="Short unique name"/><Input name="city" label="City" value="Pune"/><Input name="lat" label="Latitude" type="number"/><Input name="lng" label="Longitude" type="number"/></ManagedForm></section>
 <section className="card card-body"><h2>Add industry / sourcing capability</h2><details><summary>New industry</summary><ManagedForm kind="industry"><Input name="key" label="Short unique name"/><Input name="name" label="English name"/><Input name="hi" label="Hindi name"/><Input name="mr" label="Marathi name"/></ManagedForm></details><h3>New role</h3><ManagedForm kind="role"><Input name="key" label="Short unique name"/><Input name="name" label="Role name"/><label>Industry{select('industry',industries,'key','display_name')}</label><label>Start with settings from{select('template',configs,'id','id')}</label><Input name="skills" label="Relevant experience / skill tags, separated by commas"/><p>The role appears as a sourcing capability immediately. Complete its assessment and publish its configuration before posting jobs.</p></ManagedForm></section>
 <section className="card card-body"><h2>Experience matching rules</h2>{roles.map(role=><details key={role.key}><summary>{role.display_name}</summary><ManagedForm kind="role_rules" id={role.key}><Input name="direct" label="Direct experience tags, separated by commas" value={role.direct_tags.join(',')}/><Input name="adjacent" label="Transferable experience tags" value={role.transferable.join(',')}/><label>Skill alternatives (JSON)<textarea name="mapping" defaultValue={JSON.stringify(role.skill_mapping)}/></label></ManagedForm></details>)}</section>
 <section className="card card-body"><h2>Add a role-specific field</h2><ManagedForm kind="attribute"><Input name="key" label="Short unique name"/><Input name="name" label="English label"/><Input name="hi" label="Hindi label"/><Input name="mr" label="Marathi label"/><select name="scope"><option value="CANDIDATE_ROLE">Candidate</option><option value="JOB">Job</option></select><select name="type"><option>TEXT</option><option>BOOL</option><option>INT</option><option>ENUM</option></select><Input name="options" label="Allowed choices, separated by commas"/><Input name="freshness" label="Valid for days (blank means no expiry)" type="number"/></ManagedForm></section>
 <section className="card card-body"><h2>Role configurations</h2>{configs.map(c=><details key={c.id}><summary>{c.id} · {c.status}</summary>{c.status==='PUBLISHED'||c.status==='RETIRED'?<ManagedForm kind="clone" id={c.id}><Input name="version" label="New version"/></ManagedForm>:<ManagedForm kind="config" id={c.id}><fieldset><legend>Candidate fields (include / required)</legend>{attrs.filter(a=>a.scope!=='JOB').map(a=><div key={a.key}><label><input type="checkbox" name="fields" value={a.key} defaultChecked={c.candidate_attributes.some((v:any)=>v.key===a.key)}/>{a.display_name}</label> <label><input type="checkbox" name="required" value={a.key} defaultChecked={c.candidate_attributes.some((v:any)=>v.key===a.key&&v.required)}/>Required</label></div>)}</fieldset><fieldset><legend>Job fields (include / required)</legend>{attrs.filter(a=>a.scope==='JOB').map(a=><div key={a.key}><label><input type="checkbox" name="job_fields" value={a.key} defaultChecked={c.job_attributes.some((v:any)=>v.key===a.key)}/>{a.display_name}</label><label><input type="checkbox" name="job_required" value={a.key} defaultChecked={c.job_attributes.some((v:any)=>v.key===a.key&&v.required)}/>Required</label></div>)}</fieldset><Input name="documents" label="Document checklist keys, separated by commas" value={c.document_checklist.join(',')}/><h3>Ranking weights</h3>{Object.entries(c.scoring_weights).map(([key,v])=><Input key={key} name={'weight_'+key} label={key} value={Number(v)} type="number"/>)}<Input name="threshold" label="Assessment pass mark (%)" value={c.assessment_threshold} type="number"/><h3>Replace assessment (leave questions blank to retain current test)</h3>{[1,2,3,4,5].map(i=><details key={i}><summary>Question {i}</summary><Input name={'q'+i} label="English question"/><Input name={'hi'+i} label="Hindi question"/><Input name={'mr'+i} label="Marathi question"/><Input name={'o'+i} label="Choices separated by |"/><Input name={'oh'+i} label="Hindi choices, same order, separated by |"/><Input name={'om'+i} label="Marathi choices, same order, separated by |"/><Input name={'a'+i} label="Correct English choice (exact wording)"/></details>)}<p>Save submits this version for review. Publish from Configurations after validation.</p></ManagedForm>}</details>)}</section>
 {policies.map(p=><section className="card card-body" key={p.id}><h2>Commercial & matching defaults</h2><ManagedForm kind="commercial"><Input name="reward" label="Reward per unlock (₹)" value={Number(p.partner_reward_paise)/100} type="number"/><Input name="minimum" label="Payout minimum (₹)" value={Number(p.partner_payout_minimum_paise)/100} type="number"/><Input name="price" label="Additional unlock credit (₹)" value={Number(p.additional_credit_paise)/100} type="number"/><Input name="cap" label="Maximum endorsement boost" value={p.endorsement_cap} type="number"/><select name="salary" defaultValue={p.salary_basis}><option value="TOTAL">Fixed + maximum variable; disclose salary gap</option><option value="FIXED">Fixed salary only</option></select></ManagedForm></section>)}
 </main>;
}
