import {scopePage} from '@/lib/auth';
import Link from 'next/link';
import {sql} from '@/lib/db';
import {StatusPill} from '../../ui';
import {fmtDateTime} from '@/lib/clock';
const statuses=['APPLIED','INTERESTED','CANDIDATE_RECONFIRMED','ELIGIBILITY_CHECK','QUALIFIED','NOT_QUALIFIED','PREVIEWED','UNLOCKED','CONTACTED','INTERVIEW','SELECTED','JOINED','REJECTED','WITHDRAWN'];
export default async function Applications({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
 await scopePage('ops');
 const {q='',status=''}=await searchParams;
 const rows=await sql`SELECT a.id,a.candidate_id,a.status,a.reconfirmed_at,a.applied_at,c.name,j.title,e.brand_name FROM app.application a JOIN app.candidate c ON c.id=a.candidate_id JOIN app.job j ON j.id=a.job_id JOIN app.employer_organisation e ON e.id=j.employer_id WHERE (${status}='' OR a.status=${status}) AND (${q}='' OR c.name ILIKE ${'%'+q+'%'} OR j.title ILIKE ${'%'+q+'%'} OR a.id ILIKE ${'%'+q+'%'}) ORDER BY a.applied_at DESC,a.id`;
 return <main className="page"><div className="page-head"><h1>Applications</h1><p className="sub">Follow candidate interest and progress through hiring.</p></div><form className="card card-body mb"><div className="grid g3"><div><label htmlFor="application-search">Candidate, job or application ID</label><input id="application-search" name="q" defaultValue={q} placeholder="Search applications…"/></div><div><label htmlFor="application-status">Status</label><select id="application-status" name="status" defaultValue={status}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="btnrow"><button className="btn btn-primary">Apply filters</button><Link className="btn" href="/ops/applications">Clear</Link></div></div></form><section className="card"><div className="card-head"><h2>{rows.length} {rows.length===1?'application':'applications'}</h2></div><div className="tblwrap"><table><thead><tr><th>Application</th><th>Candidate</th><th>Job / employer</th><th>Status</th><th>Interest confirmed</th><th>Applied</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td className="id">{a.id}</td><td><Link href={'/ops/candidates/'+a.candidate_id}>{a.name}</Link></td><td>{a.title}<div className="small muted">{a.brand_name}</div></td><td><StatusPill status={a.status}/></td><td>{a.reconfirmed_at?fmtDateTime(a.reconfirmed_at):'Awaiting confirmation'}</td><td>{fmtDateTime(a.applied_at)}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty">No applications match these filters.</p>}</section></main>;
}
