import Link from 'next/link';
import {scopePage} from '@/lib/auth';
import {sql} from '@/lib/db';
import {StatusPill} from '../../ui';
import {ListToolbar,EmptyState} from '../../workspace-components';
const PAGE_SIZE=100;
export default async function Candidates({searchParams}:{searchParams:Promise<{q?:string}>}){
 await scopePage('ops');const {q=''}=await searchParams;const pattern='%'+q.trim()+'%';
 const [rows,[total]]=await Promise.all([sql`SELECT c.id,c.name,c.status,c.locality_key,p.name partner,GREATEST((SELECT max(completed_at) FROM app.assessment_attempt t WHERE t.candidate_id=c.id),(SELECT max(completed_at) FROM app.script_run r WHERE r.candidate_id=c.id AND r.status='COMPLETED')) assessed FROM app.candidate c LEFT JOIN app.attribution a ON a.candidate_id=c.id LEFT JOIN app.partner p ON p.id=a.partner_id WHERE (${q}='' OR c.name ILIKE ${pattern} OR c.id ILIKE ${pattern} OR c.locality_key ILIKE ${pattern}) ORDER BY c.id DESC LIMIT ${PAGE_SIZE}`,sql`SELECT COUNT(*)::int n FROM app.candidate c WHERE (${q}='' OR c.name ILIKE ${pattern} OR c.id ILIKE ${pattern} OR c.locality_key ILIKE ${pattern})`]);
 return <main className="page"><div className="page-head"><div className="nd-section-kicker">People &amp; progress</div><h1>Candidates</h1><p>Get to know your candidates and help them take their next step.</p></div><ListToolbar count={total.n} label="candidates" query={q} placeholder="Search name, candidate ID or locality…" action="/ops/candidates"/><section className="card"><div className="card-head"><h2>Candidate directory</h2><span className="small muted">Showing {rows.length} of {total.n}</span></div><div className="tblwrap"><table><thead><tr><th>Candidate</th><th>Profile status</th><th>Locality</th><th>Assessment</th><th>Referred by</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><Link href={'/ops/candidates/'+c.id}>{c.name||c.id}</Link><div className="id">{c.id}</div></td><td><StatusPill status={c.status}/></td><td>{c.locality_key?.replaceAll('_',' ')||'Not set'}</td><td><span className={`pill ${c.assessed?'p-ok':'p-warn'}`}>{c.assessed?'Completed':'Awaiting assessment'}</span></td><td>{c.partner||'Direct'}</td></tr>)}</tbody></table></div>{!rows.length&&<EmptyState title="No candidates found" description="Try another name, locality or candidate ID."/>}</section></main>;
}
