import Link from 'next/link';import {notFound} from 'next/navigation';
import {scopePage} from '@/lib/auth';import {sql} from '@/lib/db';import {ManagedForm} from '../../../manage/form';
export default async function EditPartner({params}:{params:Promise<{id:string}>}){
 await scopePage('ops');const {id}=await params;
 const [partners,sites,localities,roles]=await Promise.all([sql`SELECT * FROM app.partner WHERE id=${id}`,sql`SELECT * FROM app.partner_site WHERE partner_id=${id} ORDER BY id`,sql`SELECT key,display_name FROM app.locality ORDER BY display_name`,sql`SELECT key,industry_key,display_name FROM app.role_family ORDER BY display_name`]);
 const p=partners[0];if(!p)notFound();
 const locality=(value?:string)=><label className="field">Locality<select name="locality" defaultValue={value}>{localities.map(l=><option value={l.key} key={l.key}>{l.display_name}</option>)}</select></label>;
 return <main className="page"><div className="page-head"><h1>Edit {p.name}</h1><p>{p.id}</p><Link className="btn" href="/ops/partners">← Partners</Link></div><section className="card card-body"><h2>Partner details</h2><ManagedForm kind="partner" id={id}>{[['name','Partner name'],['pan','PAN'],['payout_upi','Demo payout reference']].map(([key,label])=><label className="field" key={key}>{label}<input name={key} defaultValue={p[key]||''}/></label>)}<fieldset><legend>Service localities</legend>{localities.map(l=><label key={l.key}><input type="checkbox" name="localities" value={l.key} defaultChecked={p.service_localities.includes(l.key)}/>{l.display_name} </label>)}</fieldset><fieldset><legend>Sourcing capabilities</legend>{roles.map(r=><label key={r.key}><input type="checkbox" name="capabilities" value={r.industry_key+'/'+r.key} defaultChecked={p.capabilities.includes(r.industry_key+'/'+r.key)}/>{r.display_name} </label>)}</fieldset></ManagedForm></section><section className="card card-body" id="add-site"><h2>Add a site for {p.name}</h2><ManagedForm kind="site" id={id}><label className="field">Site name<input name="name" required/></label><label className="field">Address<input name="address" required/></label>{locality()}<p>New sites require Operations verification before activation.</p></ManagedForm></section>{sites.map(s=><section className="card card-body" key={s.id} id={s.id}><h2>{s.name||s.id}</h2><p>{s.partner_code} · {s.status}</p><ManagedForm kind="site_edit" id={s.id}><label className="field">Site name<input name="name" defaultValue={s.name||s.id} required/></label><label className="field">Address<input name="address" defaultValue={s.address||''} required/></label>{locality(s.locality_key)}</ManagedForm><h3>Site status</h3><ManagedForm kind="site_status" id={s.id}><label>Status<select name="status" defaultValue={s.status}><option>ACTIVE</option><option>SUSPENDED</option><option>REVOKED</option></select></label></ManagedForm></section>)}</main>;
}
