'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {Icon} from './dashboard-icon';
const links = [
 ['/ops','Dashboard','home'],['/ops/employers','Employers','building'],['/ops/partners','Partners','users'],['/ops/candidates','Candidates','users'],['/ops/jobs','Jobs','job'],['/ops/matches','Job matches','spark'],['/ops/applications','Applications','file'],['/ops/attribution','Referrals','link'],['/ops/exceptions','Exceptions','alert'],['/ops/credit-requests','Credit requests','file'],['/ops/reports','Reports','chart'],['/ops/configurations','Configurations','settings'],['/ops/manage','Manage & catalogue','settings'],['/ops/replacements','Replacements','shield'],['/ops/fraud','Fraud review','alert'],['/ops/data-requests','Data requests','lock'],['/ops/audit','Audit trail','file'],
];
export function OpsShell({children,role}:{children:React.ReactNode;role:string}) {
 const path=usePathname(); const [open,setOpen]=useState(false);const [query,setQuery]=useState('');
 useEffect(()=>{setOpen(false);setQuery('');},[path]);
 const results=query.trim()?links.filter(([,label])=>label.toLowerCase().includes(query.trim().toLowerCase())):[];
 return <div className="nd-shell"><a className="nd-skip" href="#ops-content">Skip to content</a><aside id="ops-mobile-nav" className={`nd-sidebar ${open?'is-open':''}`}><Link href="/ops" className="nd-brand"><span className="nd-sun">☀</span><strong>NayiDisha</strong><small>Jobs. Skills. Better Futures.</small></Link><nav aria-label="Operations navigation">{links.map(([href,label,icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} aria-current={(href==='/ops'?path===href:(path.startsWith(href)||(href==='/ops/employers'&&path==='/ops/new-employer')||(href==='/ops/partners'&&path==='/ops/new-partner')))?'page':undefined}><Icon name={icon}/>{label}</Link>)}</nav><div className="nd-help"><Icon name="heart"/><strong>Need a hand?</strong><p>Explore the demo guide and available identities.</p><Link className="btn" href="/demo">Open demo guide →</Link></div></aside><div className="nd-workspace"><header className="nd-topbar"><button className="btn nd-menu" aria-expanded={open} aria-controls="ops-mobile-nav" onClick={()=>setOpen(!open)}>{open?'Close menu':'Menu'}</button><div className="nd-search"><Icon name="search"/><input aria-label="Find an operations page" placeholder="Find employers, candidates, jobs, reports…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setQuery('');}}/>{query&&<div className="nd-search-results" role="region" aria-label="Page search results">{results.length?results.map(([href,label])=><Link href={href} key={href} onClick={()=>setQuery('')}>{label} <span>→</span></Link>):<p>No pages found. Try “jobs” or “candidates”.</p>}</div>}</div><Link className="nd-notifications" href="/ops#attention" aria-label="View items needing attention"><Icon name="bell"/></Link><Link href="/demo" className="nd-profile" aria-label="Open demo identities and account controls"><span className="nd-avatar">{role==='ADMIN'?'A':'O'}</span><span><strong>{role==='ADMIN'?'Administrator':'Operations'}</strong><small>Operations workspace</small></span><span>⌄</span></Link></header><div id="ops-content" tabIndex={-1}>{children}</div></div></div>;
}
