 'use client';
import {journeyTranslations} from './translations';
import {useState,useTransition,useEffect,useRef,Fragment} from 'react';
import * as actions from './journey-actions';
export function Simulator({configs,attributes,localities,jobs,existing,source,resume}:{resume:string;configs:any[];attributes:any[];localities:any[];jobs:any[];existing:any;source:string}){
 const [step,setStep]=useState(resume==='assess'?'test':resume),[pending,start]=useTransition(),[msg,message]=useState('');
 const [lang,setLang]=useState<'en'|'hi'|'mr'>(existing?.language||'en'),[config,setConfig]=useState(existing?.role_config_id||configs[0]?.id||'');
 const [test,setTest]=useState<any>(null),[application,setApplication]=useState('');
 const [history,setHistory]=useState<{step:string}[]>([]);const current=useRef<HTMLDivElement>(null);
 useEffect(()=>{current.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[step]);
 const run=(fn:()=>Promise<void>)=>start(async()=>{message('');try{await fn();setHistory(h=>[...h,{step}]);}catch(e){message(e instanceof Error?e.message:'Please try again.');}});
 const labels={en:{start:'Start conversation',verify:'Verify mobile',consent:'Your choices',profile:'Your profile',test:'Readiness assessment',jobs:'Available jobs'},hi:{start:'बातचीत शुरू करें',verify:'मोबाइल सत्यापित करें',consent:'आपकी सहमति',profile:'आपकी प्रोफ़ाइल',test:'तैयारी परीक्षा',jobs:'उपलब्ध नौकरियाँ'},mr:{start:'संभाषण सुरू करा',verify:'मोबाइल पडताळा',consent:'तुमची संमती',profile:'तुमची माहिती',test:'तयारी चाचणी',jobs:'उपलब्ध नोकऱ्या'}}[lang];
 const tr=(s:string)=>lang==='en'?s:journeyTranslations[s]?.[lang==='hi'?0:1]||s;
 const input=(name:string,label:string,value?:any,type='text')=><label className="field">{tr(label)}<input name={name} type={type} defaultValue={value}/></label>;
 const prompts:Record<string,string>={start:'Choose your language and enter your demo mobile number to begin.',otp:'Let’s verify your demo mobile number. Enter 123456; no real OTP is sent.',consent:'You decide how your information is used. Please review your choices.',profile:'Tell us about yourself so we can find suitable work near you.',test:'Ready for a short role assessment?',jobs:'Here are the jobs currently available. Select a job to continue.',confirm:'Please confirm your interest before we share your profile with this employer.'};
 const replies:Record<string,string>={start:'Start my job search',otp:'Verify my demo number',consent:'Save my consent choices',profile:'Save my profile',test:'Continue assessment',jobs:'Apply for this job',confirm:'Confirm my interest'};
 return <>{history.map((entry,i)=><Fragment key={i}><div className="wa-msg wa-in">{prompts[entry.step]}<div className="wa-meta">NayiDisha</div></div><div className="wa-msg wa-out">{replies[entry.step]||'Continue'}<div className="wa-meta">You · ✓✓</div></div></Fragment>)}<div ref={current} className="wa-msg wa-in wa-step-prompt">{prompts[step]}<div className="wa-meta">NayiDisha</div></div><div className="wa-msg wa-in wa-reply-panel" aria-busy={pending}><p role="status">{pending?'NayiDisha is processing your reply…':msg}</p>

 {step==='start'&&<form action={f=>run(async()=>{await actions.start(String(f.get('phone')),lang,String(f.get('code')));setStep('otp');message('Demo code: 123456');})}><select value={lang} onChange={e=>setLang(e.target.value as any)}><option value="en">English</option><option value="hi">हिन्दी</option><option value="mr">मराठी</option></select>{input('phone','Demo mobile number','+910000000042')}{input('code','Partner code / source',source)}<button disabled={pending}>{labels.start}</button></form>}
 {step==='otp'&&<form action={f=>run(async()=>{const state=await actions.verify(String(f.get('code')));setStep(state.step==='assess'?'test':state.step);})}>{input('code','Demo verification code')}<button disabled={pending}>{labels.verify}</button></form>}
 {step==='consent'&&<form action={f=>run(async()=>{await actions.saveConsent(f.has('processing'),f.has('alerts'),f.has('assistance'));setStep('profile');})}><h3>{labels.consent}</h3><p>{tr("We use your name, locality, experience, availability and answers to match jobs. Contact details are shared only after you apply, reconfirm, and the employer unlocks. You can withdraw each permission later.")}</p><label><input type="checkbox" name="processing"/>{tr("Allow processing for job matching (required)")}</label><br/><label><input type="checkbox" name="alerts"/>{tr("Send me job alerts (optional)")}</label><br/><label><input type="checkbox" name="assistance"/>{tr("Allow my sourcing partner to assist me (optional)")}</label><br/><button disabled={pending}>{tr("Continue")}</button></form>}
 {step==='profile'&&<form action={f=>run(async()=>{const attrs:Record<string,string>={};for(const [k,v]of f.entries())if(k.startsWith('attr_'))attrs[k.slice(5)]=String(v);await actions.saveProfile({name:String(f.get('name')),locality:String(f.get('locality')),age18:f.has('age'),work:f.has('work'),months:Number(f.get('months')),tags:String(f.get('tags')),languages:f.getAll('languages').map(String),pay:Number(f.get('pay')),commute:Number(f.get('commute')),shifts:f.getAll('shifts').map(String),config,attributes:attrs});setStep('test');})}><h3>{labels.profile}</h3>{input('name','Name',existing?.name||'DEMO Candidate')}<label><input type="checkbox" name="age" defaultChecked={existing?.age_confirmed_18}/>{tr("I am 18 or older")}</label><br/><label><input type="checkbox" name="work" defaultChecked={existing?.work_authorised}/>{tr("I am authorised to work in India")}</label><label>{tr("Locality")}<select name="locality" defaultValue={existing?.locality_key}>{localities.map(l=><option key={l.key} value={l.key}>{l.display_name}</option>)}</select></label>{input('months','Experience in months',existing?.experience_months||0,'number')}{input('tags','Experience / skills (comma separated)',existing?.experience_tags?.join(',')||'')}{input('pay','Expected monthly pay ₹',Number(existing?.expected_pay_paise||1800000)/100,'number')}{input('commute','Maximum commute minutes',existing?.max_commute_min||45,'number')}<fieldset><legend>{tr("Languages")}</legend>{['mr','hi','en'].map(l=><label key={l}><input type="checkbox" name="languages" value={l} defaultChecked={existing?.languages?.includes(l)}/>{l} </label>)}</fieldset><fieldset><legend>{tr("Available shifts")}</legend>{Array.from(new Set(['ANY',...jobs.map(j=>j.shift)])).map(s=><label key={s}><input type="checkbox" name="shifts" value={s} defaultChecked={existing?.shift_availability?.includes(s)}/>{s==='ANY'?'Any shift':s} </label>)}</fieldset><select value={config} onChange={e=>setConfig(e.target.value)}>{configs.map(c=><option key={c.id} value={c.id}>{c.role_family_key}</option>)}</select>{attributes.filter(a=>a.scope==='CANDIDATE_ROLE'&&configs.find(c=>c.id===config)?.candidate_attributes.some((v:any)=>v.key===a.key)).map(a=><label key={a.key} className="field">{a.translations?.[lang]||a.display_name}{['BOOL','ENUM'].includes(a.data_type)?<select name={'attr_'+a.key}><option value="">{tr("Choose\u2026")}</option>{(a.data_type==='BOOL'?['true','false']:a.allowed_values).map((v:string)=><option key={v} value={v}>{v==='true'?'Yes':v==='false'?'No':v}</option>)}</select>:<input name={'attr_'+a.key} type={a.data_type==='INT'?'number':'text'}/>}</label>)}<button disabled={pending}>{tr("Save profile")}</button></form>}
 {step==='test'&&!test&&<><h3>{labels.test}</h3><button disabled={pending} onClick={()=>run(async()=>setTest(await actions.beginTest()))}>{tr("Begin timed assessment")}</button><button onClick={()=>setStep('jobs')}>{tr("Continue with existing assessment")}</button></>}
 {step==='test'&&test&&<form action={f=>run(async()=>{const result=await actions.submitTest(test.id,Object.fromEntries(f.entries()) as Record<string,string>);message('Score: '+result.score);setStep('jobs');})}><p>Complete within {test.minutes} minutes. Answers are checked on the server.</p>{test.questions.map((q:any)=><label key={q.id} className="field">{q.prompt}<select name={q.id} required><option value="">{tr("Choose\u2026")}</option>{q.options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}<button disabled={pending}>{tr("Submit assessment")}</button></form>}
 {step==='jobs'&&<><button onClick={()=>setStep('profile')}>Edit my profile and role details</button><h3>{labels.jobs}</h3>{jobs.length===0&&<p>No live jobs are available yet. Please check again later.</p>}{jobs.map(j=><div className="note" key={j.id}><strong>{j.title}</strong><p>₹{Number(j.fixed_pay_paise)/100} fixed + up to ₹{Number(j.variable_max_paise)/100} variable · {j.shift}</p><button disabled={pending} onClick={()=>run(async()=>{const a=await actions.applyJob(j.id);setApplication(a.applicationId);setStep('confirm');})}>{tr("Apply")}</button></div>)}<a href="/wa/preferences">Preferences, endorsements & my data</a></>}
 {step==='confirm'&&<><p>{tr("Your application is recorded. Please reconfirm that you want this employer to see your qualified profile and contact you.")}</p><button disabled={pending} onClick={()=>run(async()=>{const result=await actions.confirm(application);message(result.qualified?'Interest confirmed. Qualified; score '+result.score:'Interest confirmed. Missing requirements: '+result.gaps.join(', '));setStep('jobs');})}>{tr("Yes, I am interested")}</button><button onClick={()=>{message('Your application remains on hold until you confirm.');setStep('jobs');}}>{tr("Not now")}</button></>}
 </div></>;
}
