import {scopePage} from '@/lib/auth';
import {sql} from '@/lib/db';
import {WorkflowForm} from '../../workflow-form';
import {deliverDueReminders} from '../../workflow-actions';
import {EmptyState} from '../../workspace-components';
import {fmtDateTime} from '@/lib/clock';
import {StatusPill} from '../../ui';
export default async function Exceptions(){await scopePage('ops');const [messages,issues,tests,profiles]=await Promise.all([sql`SELECT id,candidate_id,body,failure_reason FROM app.message_log WHERE delivery_status='FAILED' ORDER BY created_at DESC LIMIT 100`,sql`SELECT * FROM app.workflow_issue WHERE resolved_at IS NULL ORDER BY created_at DESC LIMIT 100`,sql`SELECT id,candidate_id,expires_at FROM app.assessment_session WHERE completed_at IS NULL ORDER BY started_at DESC LIMIT 100`,sql`SELECT id,name,status FROM app.candidate WHERE status IN ('STARTED','MOBILE_VERIFIED','PROFILE_INCOMPLETE') LIMIT 100`]);
 return <main className="page"><div className="page-head"><div className="nd-section-kicker">Keep things moving</div><h1>Operational exceptions</h1><p>Review interrupted journeys and help candidates get back on track.</p></div><div className="nd-page-toolbar"><div className="btnrow"><a className="btn" href="/ops/attribution">Referral disputes</a><a className="btn" href="/ops/fraud">Fraud reviews</a></div><form action={deliverDueReminders}><button className="btn btn-primary">Deliver due demo reminders</button></form></div><div className="grid g2"><section className="card"><div className="card-head"><h2>Failed messages</h2><span className="pill p-warn">{messages.length}</span></div><div className="card-body">{!messages.length&&<EmptyState title="Messages are on track" description="No failed messages to review."/>}{messages.map(m=><section className="note mb" key={m.id}><strong>{m.candidate_id}</strong><p>{m.body}</p><p>{m.failure_reason}</p><WorkflowForm kind="retry_message" id={m.id} label="Retry simulated delivery"/></section>)}</div></section><section className="card"><div className="card-head"><h2>Verification &amp; matching</h2><span className="pill p-warn">{issues.length}</span></div><div className="card-body">{!issues.length&&<EmptyState title="All clear" description="No verification or matching issues need attention."/>}{issues.map(i=><section className="note mb" key={i.id}><a href={'/ops/candidates/'+i.candidate_id}>{i.candidate_id}</a><p>{i.kind.replaceAll('_',' ')} · {i.detail}</p><WorkflowForm kind={i.kind==='MATCHING_RETRY'?'retry_matching':'resolve_issue'} id={i.id} label={i.kind==='MATCHING_RETRY'?'Retry matching':'Mark reviewed'}/></section>)}</div></section><section className="card"><div className="card-head"><h2>Incomplete assessments</h2><span className="pill p-info">{tests.length}</span></div><div className="card-body">{!tests.length&&<EmptyState title="No assessments waiting" description="Incomplete assessments will appear here."/>}{tests.map(t=><p key={t.id}><a href={'/ops/candidates/'+t.candidate_id}>{t.candidate_id}</a><span className="small muted"> · expires {fmtDateTime(t.expires_at)}</span></p>)}</div></section><section className="card"><div className="card-head"><h2>Incomplete registrations</h2><span className="pill p-info">{profiles.length}</span></div><div className="card-body">{!profiles.length&&<EmptyState title="Profiles are up to date" description="Registrations that need follow-up will appear here."/>}{profiles.map(c=><p className="flexb" key={c.id}><a href={'/ops/candidates/'+c.id}>{c.name||c.id}</a><StatusPill status={c.status}/></p>)}</div></section></div></main>;
}
