'use server';
import {sql} from '@/lib/db';import {requireRole} from '@/lib/auth';import {now} from '@/lib/clock';import {nextId} from '@/lib/ids';import {revalidatePath} from 'next/cache';import {refreshCandidate} from '@/modules/discovery';import {messagingProvider} from '@/modules/adapters/messaging';
export async function workflow(f:FormData){const kind=String(f.get('kind')),id=String(f.get('id')),reason=String(f.get('reason')||'').trim();const at=await now();let actor;
if(['remind','withdraw','decline_suggestion'].includes(kind)){
 actor=await requireRole(['CANDIDATE']);
 if(kind==='decline_suggestion'){await sql`UPDATE app.job_suggestion SET hidden=true,reason='Candidate not interested' WHERE candidate_id=${actor.id} AND job_id=${id}`;}else if(kind==='withdraw'){const rows=await sql`UPDATE app.application SET status='WITHDRAWN',status_at=${at} WHERE id=${id} AND candidate_id=${actor.id} AND status NOT IN ('JOINED','WITHDRAWN','REJECTED') RETURNING id`;if(!rows.length)throw new Error('Application cannot be withdrawn.');}
 else{const [j]=await sql`SELECT id FROM app.job WHERE id=${id} AND status='LIVE' AND (expires_at IS NULL OR expires_at>${at})`;if(!j)throw new Error('Job is no longer available.');await sql`INSERT INTO app.candidate_reminder(candidate_id,job_id,due_at) VALUES(${actor.id},${id},${new Date(at.getTime()+86400000)}) ON CONFLICT(candidate_id,job_id) DO UPDATE SET due_at=EXCLUDED.due_at,sent_at=NULL`;}
}else if(['request_credits','submit_job','save_organisation','edit_job'].includes(kind)){
 actor=await requireRole(['EMPLOYER','PARTNER']);
 if(kind==='save_organisation'){if(!String(f.get('name')||'').trim())throw new Error('Name is required.');if(actor.role==='EMPLOYER')await sql`UPDATE app.employer_organisation SET brand_name=${String(f.get('name')||'').trim()},billing_contact=${String(f.get('contact')||'')} WHERE id=${actor.id}`;else await sql`UPDATE app.partner SET name=${String(f.get('name')||'').trim()},payout_upi=${String(f.get('contact')||'')} WHERE id=${actor.id}`;}
 else {if(actor.role!=='EMPLOYER')throw new Error('Employer account required.');const [job]=await sql`SELECT * FROM app.job WHERE id=${id} AND employer_id=${actor.id}`;if(!job)throw new Error('Job outside your account.');
 if(kind==='edit_job'){if(job.status!=='DRAFT')throw new Error('Return the job to draft before editing these details.');const title=String(f.get('title')||'').trim(),closing=String(f.get('closing')||'');const ends=closing?new Date(closing):null;if(!title||ends&&(!Number.isFinite(ends.getTime())||ends<=at))throw new Error('Enter a title and a future closing date.');await sql`UPDATE app.job SET title=${title},description=${String(f.get('description')||'')},preferred_skills=${String(f.get('preferred')||'')},qualification=${String(f.get('qualification')||'')},expires_at=${ends} WHERE id=${id}`;}else if(kind==='submit_job'){if(job.status!=='DRAFT')throw new Error('Only draft or returned jobs can be submitted.');await sql`UPDATE app.job SET status='PENDING_APPROVAL',status_reason=NULL WHERE id=${id}`;}
 else{const quantity=Number(f.get('quantity'));if(!Number.isSafeInteger(quantity)||quantity<1||quantity>100||!reason)throw new Error('Enter 1–100 credits and a reason.');await sql`INSERT INTO app.credit_request(id,employer_id,job_id,quantity,reason) VALUES(${await nextId('REQ')},${actor.id},${id},${quantity},${reason})`;}}
}else{
 actor=await requireRole(['ADMIN','OPERATIONS']);
 if(['return_job','hide_match','restore_match','manual_match','decide_credit'].includes(kind)&&!reason)throw new Error('A reason is required.');
 if(kind==='return_job'){const rows=await sql`UPDATE app.job SET status='DRAFT',status_reason=${reason} WHERE id=${id} AND status='PENDING_APPROVAL' RETURNING id`;if(!rows.length)throw new Error('Job is not awaiting approval.');}
 else if(kind==='recompute'){await refreshCandidate(id);}
 else if(kind==='manual_match'){await refreshCandidate(id);const job=String(f.get('job'));const [s]=await sql`SELECT eligible FROM app.job_suggestion WHERE candidate_id=${id} AND job_id=${job}`;if(!s)throw new Error('Select a live job.');if(!s.eligible)throw new Error('Candidate does not meet eligibility. Manual review cannot bypass requirements.');await sql`UPDATE app.job_suggestion SET hidden=false,reason=${reason} WHERE candidate_id=${id} AND job_id=${job}`;}
 else if(kind==='hide_match'||kind==='restore_match'){await sql`UPDATE app.job_suggestion SET hidden=${kind==='hide_match'},reason=${reason} WHERE candidate_id=${id} AND job_id=${String(f.get('job'))}`;}
 else if(kind==='decide_credit'){await sql.begin(async tx=>{const [q]=await tx`SELECT * FROM app.credit_request WHERE id=${id} AND status='PENDING' FOR UPDATE`;if(!q)throw new Error('Request already decided.');const approve=f.get('decision')==='APPROVED';if(approve){const [ent]=await tx`SELECT id FROM app.posting_entitlement WHERE job_id=${q.job_id} AND ends_at>${at}`;if(!ent)throw new Error('No active posting entitlement.');const [p]=await tx`SELECT additional_credit_paise FROM app.commercial_policy WHERE active`;await tx`INSERT INTO app.credit_ledger(id,entitlement_id,entry_type,credit_delta,amount_paise,note,created_at) VALUES(${await nextId('CRD',tx)},${ent.id},'PURCHASE',${q.quantity},${Number(p.additional_credit_paise)*q.quantity},${'Approved demo request '+id},${at})`;}
 await tx`UPDATE app.credit_request SET status=${approve?'APPROVED':'REJECTED'},decision_reason=${reason},decided_at=${at} WHERE id=${id}`;});}
 else if(kind==='retry_message'){const [m]=await sql`SELECT * FROM app.message_log WHERE id=${id} AND delivery_status='FAILED'`;if(!m)throw new Error('No failed message found.');const [flags]=await sql`SELECT messaging_failure FROM app.demo_clock WHERE id=1`;if(flags.messaging_failure)throw new Error('Turn off simulated message failure before retrying.');await sql`UPDATE app.message_log SET delivery_status='DELIVERED',failure_reason=NULL WHERE id=${id}`;}
 else if(kind==='resolve_issue'){await sql`UPDATE app.workflow_issue SET resolved_at=${at} WHERE id=${id}`;}
 else if(kind==='retry_matching'){const [issue]=await sql`SELECT candidate_id FROM app.workflow_issue WHERE id=${id} AND resolved_at IS NULL`;if(!issue)throw new Error('Issue already resolved.');await refreshCandidate(issue.candidate_id);await sql`UPDATE app.workflow_issue SET resolved_at=${at} WHERE id=${id}`;}
 else throw new Error('Unknown action.');
}
await sql`INSERT INTO app.action_audit(actor,role,action,entity_id,detail) VALUES(${actor.id},${actor.role},${kind},${id},${sql.json({reason})})`;revalidatePath('/','layout');return kind==='remind'?'Reminder set for tomorrow on the demo clock.':'Saved.';
}
export async function deliverDueReminders(){await requireRole(['ADMIN','OPERATIONS']);const at=await now();const rows=await sql`SELECT r.*,c.language,c.alert_quiet_from,c.alert_quiet_to,c.alert_max_per_week,j.title,j.fixed_pay_paise,e.brand_name,l.name locality FROM app.candidate_reminder r JOIN app.candidate c ON c.id=r.candidate_id JOIN app.job j ON j.id=r.job_id JOIN app.employer_organisation e ON e.id=j.employer_id JOIN app.employer_location l ON l.id=j.location_id WHERE r.sent_at IS NULL AND r.due_at<=${at} AND j.status='LIVE' AND e.status='VERIFIED' AND (j.expires_at IS NULL OR j.expires_at>${at}) AND EXISTS(SELECT 1 FROM app.consent_record cr WHERE cr.candidate_id=c.id AND cr.purpose='JOB_ALERTS' AND cr.granted_at IS NOT NULL AND cr.withdrawn_at IS NULL)`;
for(const r of rows){const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'numeric',hourCycle:'h23'}).format(at));const quiet=r.alert_quiet_from<r.alert_quiet_to?hour>=r.alert_quiet_from&&hour<r.alert_quiet_to:hour>=r.alert_quiet_from||hour<r.alert_quiet_to;if(quiet)continue;const [n]=await sql`SELECT count(*) n FROM app.message_log WHERE candidate_id=${r.candidate_id} AND category='MARKETING' AND delivery_status='DELIVERED' AND created_at>${new Date(at.getTime()-7*86400000)}`;if(Number(n.n)>=r.alert_max_per_week)continue;
const claimed=await sql`UPDATE app.candidate_reminder SET sent_at=${at} WHERE candidate_id=${r.candidate_id} AND job_id=${r.job_id} AND sent_at IS NULL RETURNING job_id`;if(!claimed.length)continue;
try{const m=await messagingProvider().send({candidateId:r.candidate_id,language:r.language,templateKey:'job_alert',variables:{title:r.title,employer:r.brand_name,locality:r.locality,fixed:'₹'+Number(r.fixed_pay_paise)/100,minutes:'see job details'}});const [delivered]=await sql`SELECT delivery_status FROM app.message_log WHERE id=${m.id}`;if(delivered.delivery_status!=='DELIVERED')await sql`UPDATE app.candidate_reminder SET sent_at=NULL WHERE candidate_id=${r.candidate_id} AND job_id=${r.job_id}`;}catch{await sql`UPDATE app.candidate_reminder SET sent_at=NULL WHERE candidate_id=${r.candidate_id} AND job_id=${r.job_id}`;}}
revalidatePath('/','layout');}
